/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    docs: Doc;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Leave blank to generate from the title.
   */
  slug: string;
  layout: (
    | HeroBlock
    | RichTextBlock
    | MediaBlock
    | FeatureGridBlock
    | IndustriesBlock
    | ProcessStepsBlock
    | CoverageBlock
    | LogoWallBlock
    | WhyUsBlock
    | CallToActionBlock
    | FaqBlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant?: ('banner' | 'centered' | 'split' | 'minimal') | null;
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  image?: (number | null) | Media;
  /**
   * Crossfades behind the banner. One image is fine.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Partner marks that scroll along the bottom of the banner.
   */
  marqueeLogos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  actions?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'docs';
                value: number | Doc;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
          appearance?: ('primary' | 'secondary' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers. Required.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Leave blank to generate from the title.
   */
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt: string;
  authors?: (number | User)[] | null;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  /**
   * Shown on posts this user is credited as author of.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Leave blank to generate from the title.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  title: string;
  /**
   * Leave blank to generate from the title.
   */
  slug: string;
  /**
   * Used for search results and meta description.
   */
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Leave empty for a top-level section.
   */
  parent?: (number | null) | Doc;
  /**
   * Lower numbers sort first within the same parent.
   */
  order: number;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  layout?: ('default' | 'editorial' | 'split') | null;
  width?: ('prose' | 'full') | null;
  eyebrow?: string | null;
  /**
   * Wrap the closing words in *asterisks* to set them in red italics.
   */
  heading?: string | null;
  /**
   * Turns a long passage into numbered beats separated by hairlines.
   */
  numbered?: boolean | null;
  /**
   * One image fills the column; two are offset into a collage.
   */
  media?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  mediaPosition?: ('left' | 'right') | null;
  /**
   * Renders the opening paragraph larger and darker.
   */
  lede?: boolean | null;
  /**
   * On by default: a long passage shows its opening and the reader expands the rest. Copy that already fits is never clamped, whatever this says. Untick to publish the passage open.
   */
  collapsible?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  caption?: string | null;
  size?: ('contained' | 'full') | null;
  aspect?: ('natural' | 'wide' | 'cinematic') | null;
  /**
   * Optional label set over the image, e.g. a site or project name.
   */
  overline?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  intro?: string | null;
  display?: ('grid' | 'carousel') | null;
  columns?: ('2' | '3' | '4') | null;
  features: {
    /**
     * Line icon drawn by the frontend. Overrides an uploaded icon.
     */
    iconName?:
      | ('cpu' | 'dashboard' | 'screen' | 'network' | 'signal' | 'cabinet' | 'cog' | 'refresh' | 'shield' | 'gauge')
      | null;
    icon?: (number | null) | Media;
    title: string;
    description?: string | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      label?: string | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'docs';
            value: number | Doc;
          } | null);
      url?: string | null;
      newTab?: boolean | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock".
 */
export interface IndustriesBlock {
  eyebrow?: string | null;
  /**
   * Wrap the closing words in *asterisks* to set them in the red italic accent.
   */
  heading?: string | null;
  /**
   * Sits beside the heading — one or two sentences reads best.
   */
  intro?: string | null;
  /**
   * One card each. Six to eight sectors keep the track readable.
   */
  sectors: {
    name: string;
    iconName?: ('oil' | 'water' | 'beverage' | 'pharma' | 'power' | 'factory' | 'chemical' | 'logistics') | null;
    /**
     * What the work looks like in this sector — one or two sentences.
     */
    description?: string | null;
    id?: string | null;
  }[];
  /**
   * Optional closing line under the index.
   */
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'industries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  eyebrow?: string | null;
  /**
   * Wrap the closing words in *asterisks* to set them in the red italic accent.
   */
  heading?: string | null;
  intro?: string | null;
  steps: {
    title: string;
    description?: string | null;
    /**
     * Optional short line above the title — e.g. "On-site" or "1–2 days".
     */
    meta?: string | null;
    id?: string | null;
  }[];
  /**
   * Optional line under the stages, for a caveat or a handover promise.
   */
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoverageBlock".
 */
export interface CoverageBlock {
  eyebrow?: string | null;
  /**
   * Wrap the closing words in *asterisks* to set them in the red italic accent.
   */
  heading?: string | null;
  tone?: ('dark' | 'light') | null;
  /**
   * Short response-time claim, set in a panel beside the heading.
   */
  note?: string | null;
  /**
   * Four areas fill the rail on desktop; more wrap onto a second row.
   */
  areas: {
    name: string;
    /**
     * One line naming the zones or towns the area covers.
     */
    note?: string | null;
    id?: string | null;
  }[];
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coverage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock".
 */
export interface LogoWallBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  layout?: ('grid' | 'marquee') | null;
  logos: {
    image: number | Media;
    name?: string | null;
    url?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoWall';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock".
 */
export interface WhyUsBlock {
  eyebrow?: string | null;
  /**
   * Wrap the closing words in *asterisks* to set them in the red italic accent.
   */
  heading?: string | null;
  /**
   * Sits beside the heading — one or two sentences reads best.
   */
  intro?: string | null;
  /**
   * The number strip under the heading. Keep each value to a few characters — "28+", "6", "1".
   */
  proofs?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Three columns read best on desktop; more wrap onto a second row.
   */
  pillars: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  /**
   * Optional closing line under the columns.
   */
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Vary this between CTAs on the same page so they do not read as repeats.
   */
  variant?: ('dark' | 'light' | 'compact') | null;
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  actions?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'docs';
                value: number | Doc;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
          appearance?: ('primary' | 'secondary' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  /**
   * Red kicker above the heading. Defaults to "Knowledge Base".
   */
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        media?: T | MediaBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        industries?: T | IndustriesBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        coverage?: T | CoverageBlockSelect<T>;
        logoWall?: T | LogoWallBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  image?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  marqueeLogos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  actions?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  layout?: T;
  width?: T;
  eyebrow?: T;
  heading?: T;
  numbered?: T;
  media?:
    | T
    | {
        image?: T;
        id?: T;
      };
  mediaPosition?: T;
  lede?: T;
  collapsible?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  size?: T;
  aspect?: T;
  overline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  display?: T;
  columns?: T;
  features?:
    | T
    | {
        iconName?: T;
        icon?: T;
        title?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock_select".
 */
export interface IndustriesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  sectors?:
    | T
    | {
        name?: T;
        iconName?: T;
        description?: T;
        id?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        meta?: T;
        id?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoverageBlock_select".
 */
export interface CoverageBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  tone?: T;
  note?: T;
  areas?:
    | T
    | {
        name?: T;
        note?: T;
        id?: T;
      };
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock_select".
 */
export interface LogoWallBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  layout?: T;
  logos?:
    | T
    | {
        image?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock_select".
 */
export interface WhyUsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  proofs?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  pillars?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  actions?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  publishedAt?: T;
  authors?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  parent?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'docs';
                value: number | Doc;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                label: string;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'docs';
                      value: number | Doc;
                    } | null);
                url?: string | null;
                newTab?: boolean | null;
              };
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'docs';
                value: number | Doc;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
          appearance?: ('primary' | 'secondary' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                label: string;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'docs';
                      value: number | Doc;
                    } | null);
                url?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  socials?:
    | {
        platform: 'x' | 'linkedin' | 'github' | 'youtube' | 'instagram' | 'facebook';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  logo?: (number | null) | Media;
  /**
   * Used in the footer. Falls back to the main logo.
   */
  logoInverse?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    newTab?: T;
                  };
              description?: T;
              id?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
              appearance?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  logo?: T;
  logoInverse?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}